In [1]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('/kaggle/input/breast-cancer-wisconsin-data/data.csv')
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pan

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [4]:
df.describe()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pan

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [6]:
df.head(5)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

**Preprocessing**

In [8]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [9]:
#As output has alphabets instead of 0 and 1
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [10]:
y_test

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1])

**Converting numpy array to tensors**

In [11]:
x_train_tensor=torch.from_numpy(x_train)
y_train_tensor=torch.from_numpy(y_train)
x_test_tensor=torch.from_numpy(x_test)
y_test_tensor=torch.from_numpy(y_test)

In [12]:
x_test_tensor

tensor([[ 0.1069,  1.0918,  0.0751,  ..., -0.7289, -0.6253, -0.6423],
        [ 0.8306,  0.6326,  0.7716,  ...,  1.2469,  0.5234, -0.4621],
        [ 0.0816, -1.2725,  0.0461,  ..., -0.1552, -0.4863, -0.3287],
        ...,
        [-0.5548,  2.4930, -0.6263,  ..., -1.7933, -0.8123, -0.9219],
        [-1.1461, -1.0605, -1.1526,  ..., -1.3981,  1.0878, -0.2119],
        [ 1.0615,  0.2770,  1.0497,  ...,  0.4884,  0.5813, -0.4315]],
       dtype=torch.float64)

In [13]:
df.shape

(569, 31)

In [38]:
# Creating a constructor
class mysimpleNN:
  def __init__(self,x):
    # initialing weights with random values and weight tensor should have no. of rows as the no. of input 
    # columns and 1 columns...for each weight there is a random value
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    # As we are only using one perceptron , we need 1 bias only and that is initiliase to 0
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

    #calculating forward propogation
  def forward(self,x):
      z=torch.matmul(x,self.weights)+self.bias
      y_pred=torch.sigmoid(z)
      return y_pred
  #calculating loss
  def calculate_loss(self,y_pred,y):
      # as we are using loss , so we want to avoid the situation where we get log 0 or log 1 ,so we clamp our 
      # predicted values  between 10^-7 and 0.9999999
      epsilon=1e-7
      y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

      #using binary cross entropy formula
      loss= -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
      return loss

In [43]:
learning_rate=0.1
epochs=30

In [44]:
model=mysimpleNN(x_train_tensor)
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [45]:
for epoch in range(epochs):
    #forward pass
    y_pred=model.forward(x_train_tensor)

    #loss 
    loss=model.calculate_loss(y_pred,y_train_tensor)
  
    #backpropagation and using auto grad to calculate gradients
    loss.backward()

    # updating weights
    # as weights are being tracked by autograd , we dont want to calculate gradient while upgrading weights so 
    # for this , we turn off gradient searching using torch.no_grad_
    with torch.no_grad():
     model.weights-=learning_rate*model.weights.grad
     model.bias-=learning_rate*model.bias.grad

    #intialzing those grads to 0 again to prevent multiplication of old gradient to new gradient giviing completely
    # wrong value of gradients
    model.weights.grad.zero_()
    model.weights.grad.zero_()

    print(f'epoch:{epoch+1},loss is :{loss}')
    
     

epoch:1,loss is :4.280170436783532
epoch:2,loss is :4.171471872177106
epoch:3,loss is :4.0572615954416005
epoch:4,loss is :3.9370763119894665
epoch:5,loss is :3.8145407403804086
epoch:6,loss is :3.6864515662187016
epoch:7,loss is :3.5536192786898235
epoch:8,loss is :3.4168499345390617
epoch:9,loss is :3.2791843453058465
epoch:10,loss is :3.14000774700089
epoch:11,loss is :2.994746125637901
epoch:12,loss is :2.8415605755979003
epoch:13,loss is :2.6840391597834214
epoch:14,loss is :2.528019966074462
epoch:15,loss is :2.36927061564442
epoch:16,loss is :2.208486839014147
epoch:17,loss is :2.0517613918701296
epoch:18,loss is :1.8984492252683305
epoch:19,loss is :1.754142183442017
epoch:20,loss is :1.6188502640822793
epoch:21,loss is :1.4878522122338729
epoch:22,loss is :1.3679718906147582
epoch:23,loss is :1.2621526252187318
epoch:24,loss is :1.1678804968709244
epoch:25,loss is :1.0881617257714309
epoch:26,loss is :1.0220251677369032
epoch:27,loss is :0.9681213670660788
epoch:28,loss is :0.

In [46]:
model.weights

tensor([[ 0.3642],
        [-0.2677],
        [ 0.3039],
        [ 0.1861],
        [-0.1412],
        [ 0.1931],
        [ 0.0999],
        [-0.2209],
        [-0.2313],
        [ 0.1627],
        [ 0.2250],
        [ 0.5215],
        [-0.3620],
        [ 0.1216],
        [ 0.5719],
        [ 0.0594],
        [ 0.1941],
        [-0.0801],
        [ 0.2778],
        [-0.0685],
        [ 0.1769],
        [ 0.4428],
        [-0.1009],
        [ 0.1839],
        [ 0.3889],
        [-0.2736],
        [-0.5665],
        [-0.3361],
        [ 0.3625],
        [-0.0476]], dtype=torch.float64, requires_grad=True)

In [47]:
model.bias

tensor([-0.3174], dtype=torch.float64, requires_grad=True)

**Model Evaluation**

In [48]:
with torch.no_grad():
    y_pred=model.forward(x_test_tensor)
    print(y_pred)

tensor([[0.3795],
        [0.2605],
        [0.2631],
        [0.3333],
        [0.2535],
        [0.5099],
        [0.2433],
        [0.3412],
        [0.2677],
        [0.3903],
        [0.3886],
        [0.2988],
        [0.8056],
        [0.6716],
        [0.3693],
        [0.2348],
        [0.2869],
        [0.0946],
        [0.2928],
        [0.4977],
        [0.2777],
        [0.4386],
        [0.4182],
        [0.3957],
        [0.1652],
        [0.3627],
        [0.2556],
        [0.7771],
        [0.3730],
        [0.3024],
        [0.3008],
        [0.5335],
        [0.6174],
        [0.2974],
        [0.2816],
        [0.1235],
        [0.3272],
        [0.6900],
        [0.5836],
        [0.1457],
        [0.7671],
        [0.2165],
        [0.4101],
        [0.2335],
        [0.9961],
        [0.3441],
        [0.8912],
        [0.8821],
        [0.7411],
        [0.1546],
        [0.6120],
        [0.2322],
        [0.6846],
        [0.1909],
        [0.2723],
        [0

In [52]:
# As predicted values are between 0.1 and 0.9 and we have 0 and 1 only as output, so we change value of y_pred as 
# 1 if it is more than 0.8 and 0 if it is less than 0.5

y_pred=(y_pred>0.8).float()
accuracy=(y_pred==y_test_tensor).float().mean()
print(f'Accuracy:{accuracy}')

Accuracy:0.5730994343757629
